version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

networks:
  app-network:
    driver: bridge
